[phases.setup]
nixPkgs = ["python311", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = ["python -m ensurepip --upgrade", "python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8000" 