[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "on_failure"

[env]
PYTHON_VERSION = "3.11"

[[services]]
name = "ai-email-processor-backend"
buildCommand = "pip install -r requirements.txt"
startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port 8000"
healthcheckPath = "/health"
healthcheckTimeout = 300

[[services]]
name = "ai-email-processor-frontend"
buildCommand = "cd frontend && npm install && npm run build"
startCommand = "cd frontend && npm start"
healthcheckPath = "/"
healthcheckTimeout = 300 